version: '3.8'

networks:
  node-app-network:
    driver: bridge

services:
  database:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=node_app
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - node-app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
  node-app:
    build:
      context: .
    container_name: node-app
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=node_app
    volumes:
      - /usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - node-app-network
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - "./src/nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - node-app
    networks:
      - node-app-network
